apiVersion: apps/v1
kind: Deployment
metadata:
  name: derecho-worker
  namespace: derecho-workspace
  labels:
    app.kubernetes.io/name: derecho-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: derecho-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: derecho-worker
      name: derecho-worker
    spec:
      containers:
      - name: derecho-worker
        image: derecho-dev
        resources:
          requests: 
            cpu: "1000m"
            memory: "500Mi"
          limits:
            cpu: "2000m"
            memory: "1000Mi"
        command:
          - "sleep"
        args:
          - "2592000" # 3600 * 24 * 30
      restartPolicy: Always
      tolerations:
      - key: "node.kubernetes.io/unschedulable"
        operator: "Exists"
        effect: "NoSchedule"
      nodeName: 10.0.0.252
          
